<script setup lang="ts">
import { mockJobProfile, mockMatches } from '@ai-talent-agent/shared';
</script>
<template>
  <main class="mx-auto max-w-7xl px-4 py-8 md:px-8">
    <section class="rounded-3xl bg-white p-6 shadow-sm"><div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 class="text-2xl font-bold">{{ mockJobProfile.title }}</h1><p class="mt-2 text-slate-600">{{ mockJobProfile.seniority }} · {{ mockMatches.length }} 位候选人推荐</p></div><RouterLink to="/hr/job/new" class="rounded-xl border border-blue-200 px-4 py-2 text-[#004ac6]">修改 JD</RouterLink></div></section>
    <section class="mt-6 grid gap-6 lg:grid-cols-[240px_1fr]">
      <aside class="space-y-4"><div class="rounded-2xl bg-white p-5 shadow-sm"><h2 class="font-bold">筛选条件</h2><label class="mt-4 block text-sm"><input type="checkbox" checked /> 高度匹配（80+）</label><label class="mt-3 block text-sm"><input type="checkbox" checked /> 卓越匹配（90+）</label></div><div class="rounded-2xl bg-blue-50 p-5 text-sm text-slate-700"><strong>AI 寻才建议</strong><p class="mt-2">建议放宽行业背景限制，当前 JD 对金融背景要求过高。</p></div></aside>
      <div class="space-y-4"><div class="flex justify-between"><h2 class="font-bold">找到 {{ mockMatches.length }} 位匹配候选人</h2><span class="text-sm text-slate-500">排序：AI 综合评分</span></div><article v-for="match in mockMatches" :key="match.candidate.id" class="rounded-3xl bg-white p-5 shadow-sm"><div class="grid gap-5 lg:grid-cols-[180px_1fr_160px]"><div><h3 class="text-lg font-bold">{{ match.candidate.name }}</h3><p class="mt-1 text-sm text-slate-600">{{ match.candidate.title }}</p><p class="mt-1 text-sm text-slate-500">{{ match.candidate.experienceYears }} 年经验 · {{ match.candidate.education }}</p><div class="mt-4 grid h-20 w-20 place-items-center rounded-full border-8 border-blue-100 text-2xl font-bold text-[#004ac6]">{{ match.totalScore }}</div></div><div><div class="grid grid-cols-4 gap-2 text-center text-sm"><div class="rounded-xl bg-blue-50 p-2">经验<br><b>{{ match.breakdown.experience }}</b></div><div class="rounded-xl bg-blue-50 p-2">技能<br><b>{{ match.breakdown.skills }}</b></div><div class="rounded-xl bg-blue-50 p-2">画像<br><b>{{ match.breakdown.profile }}</b></div><div class="rounded-xl bg-blue-50 p-2">倾向<br><b>{{ match.breakdown.careerPreference }}</b></div></div><div class="mt-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900"><strong>AI 推荐理由</strong><ul class="mt-2 list-disc pl-5"><li v-for="item in match.reasons" :key="item">{{ item }}</li></ul></div><div class="mt-3 flex flex-wrap gap-2"><span v-for="item in match.risks" :key="item" class="rounded-full bg-rose-50 px-3 py-1 text-xs text-rose-700">{{ item }}</span></div></div><div class="space-y-2"><RouterLink :to="`/hr/candidates/${match.candidate.id}`" class="block rounded-xl bg-[#004ac6] py-2 text-center font-semibold text-white">查看详情</RouterLink><button class="w-full rounded-xl border border-blue-100 py-2 text-sm">复制摘要</button><button class="w-full rounded-xl border border-blue-100 py-2 text-sm">加入导出包</button></div></div></article></div>
    </section>
  </main>
</template>
