<script setup lang="ts">
const formats = ['Excel / CSV 候选人表', '邮件正文', '飞书 / 企业微信摘要', '面试评价表（PDF）', '标准 JSON 格式'];
</script>
<template>
  <main class="mx-auto max-w-7xl px-4 py-8 md:px-8">
    <div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 class="text-2xl font-bold">HR 数据导出工作站</h1><p class="mt-2 text-slate-600">将 AI 筛选结果快速同步至您的现有工作流。</p></div><button class="rounded-xl bg-[#004ac6] px-5 py-3 font-semibold text-white">生成 ATS 导入包</button></div>
    <section class="mt-8 grid gap-6 lg:grid-cols-[320px_1fr]">
      <aside class="space-y-5"><div class="rounded-3xl bg-white p-5 shadow-sm"><h2 class="font-bold">导出格式</h2><div class="mt-4 space-y-3"><label v-for="format in formats" :key="format" class="flex items-center justify-between rounded-xl border border-blue-100 p-3 text-sm"><span>{{ format }}</span><input type="radio" name="format" /></label></div></div><div class="rounded-3xl bg-white p-5 shadow-sm"><h2 class="font-bold">字段预览与筛选</h2><div class="mt-4 space-y-3 text-sm"><label class="block"><input type="checkbox" checked /> 姓名 / 手机号</label><label class="block"><input type="checkbox" checked /> AI 综合评分</label><label class="block"><input type="checkbox" checked /> 核心技能匹配度</label><label class="block"><input type="checkbox" checked /> 风险预警</label></div></div></aside>
      <section class="rounded-3xl bg-white p-6 shadow-sm"><div class="mb-4 flex justify-between"><h2 class="font-bold">数据预览</h2><span class="text-sm text-slate-500">正在预览前 10 条数据</span></div><div class="overflow-x-auto"><table class="w-full min-w-[720px] border-collapse text-sm"><thead><tr class="bg-blue-50 text-left"><th class="p-3">序号</th><th class="p-3">人才名称</th><th class="p-3">AI 评分</th><th class="p-3">匹配关键点</th><th class="p-3">当前薪资</th><th class="p-3">风险预警</th></tr></thead><tbody><tr class="border-b"><td class="p-3">1</td><td class="p-3">张三（Senior Dev）</td><td class="p-3 text-emerald-700">94%</td><td class="p-3">7年后端架构，云原生专家</td><td class="p-3">45k/mo</td><td class="p-3">无</td></tr><tr class="border-b"><td class="p-3">2</td><td class="p-3">李四（Product Manager）</td><td class="p-3 text-emerald-700">88%</td><td class="p-3">50w+ DAU 产品经验</td><td class="p-3">38k/mo</td><td class="p-3 text-rose-600">跳槽频繁</td></tr></tbody></table></div><div class="mt-6 grid gap-3 md:grid-cols-4"><button class="rounded-xl bg-blue-50 p-4 font-semibold text-[#004ac6]">下载 Excel</button><button class="rounded-xl bg-blue-50 p-4 font-semibold text-[#004ac6]">复制邮件正文</button><button class="rounded-xl bg-blue-50 p-4 font-semibold text-[#004ac6]">复制协作摘要</button><button class="rounded-xl bg-blue-50 p-4 font-semibold text-[#004ac6]">下载 JSON</button></div></section>
    </section>
  </main>
</template>
